const $ = (selector) => document.querySelector(selector);
const money = new Intl.NumberFormat('es-AR', { style: 'currency', currency: 'ARS', maximumFractionDigits: 0 });
let products = []; let key = sessionStorage.getItem('smg-admin-key') || '';
const headers = () => ({ 'Content-Type': 'application/json', Authorization: `Bearer ${key}` });
function resetForm() { $('#product-form').reset(); $('#product-id').value = ''; $('#form-active').checked = true; $('#form-submit').textContent = 'Guardar producto'; }
function render() { const query = $('#admin-search').value.trim().toLowerCase(); const list = products.filter((product) => `${product.code} ${product.name}`.toLowerCase().includes(query)); $('#admin-products').innerHTML = list.map((product) => `<tr><td><strong>${product.code}</strong></td><td>${product.name}</td><td>${product.category}</td><td>${money.format(product.price)}</td><td><span class="status ${product.active ? 'active' : ''}">${product.active ? 'Visible' : 'Oculto'}</span></td><td><button class="table-action" data-edit="${product.id}">Editar</button><button class="table-action danger" data-delete="${product.id}">Ocultar</button></td></tr>`).join(''); }
async function readResponse(response) {
  const contentType = response.headers.get('content-type') || '';
  if (!contentType.includes('application/json')) throw new Error('La API no está disponible. Abrí la tienda con `vercel dev` o desde tu URL publicada en Vercel, no con un servidor estático.');
  return response.json();
}
async function loadProducts() { const response = await fetch('/api/products', { headers: headers() }); const data = await readResponse(response); if (!response.ok) throw new Error(data.error || 'No se pudo iniciar sesión.'); products = data; $('#admin-login').hidden = true; $('#admin-content').hidden = false; render(); }
$('#login-button').addEventListener('click', async () => { key = $('#admin-key').value.trim(); try { await loadProducts(); sessionStorage.setItem('smg-admin-key', key); } catch (error) { alert(error.message); } });
$('#product-form').addEventListener('submit', async (event) => { event.preventDefault(); const id = $('#product-id').value; const body = { code: $('#form-code').value, name: $('#form-name').value, category: $('#form-category').value, price: Number($('#form-price').value), imageUrl: $('#form-image-url').value, active: $('#form-active').checked }; const response = await fetch(id ? `/api/products/${id}` : '/api/products', { method: id ? 'PATCH' : 'POST', headers: headers(), body: JSON.stringify(body) }); const data = response.status === 204 ? null : await response.json(); if (!response.ok) return alert(data.error || 'No se pudo guardar.'); await loadProducts(); resetForm(); });
$('#admin-products').addEventListener('click', async (event) => { const edit = event.target.closest('[data-edit]'); const remove = event.target.closest('[data-delete]'); if (edit) { const product = products.find((item) => item.id === Number(edit.dataset.edit)); $('#product-id').value = product.id; $('#form-code').value = product.code; $('#form-name').value = product.name; $('#form-category').value = product.category; $('#form-price').value = product.price; $('#form-image-url').value = product.imageUrl || ''; $('#form-active').checked = product.active; $('#form-submit').textContent = 'Guardar cambios'; window.scrollTo({ top: 0, behavior: 'smooth' }); } if (remove && confirm('¿Ocultar este producto de la tienda?')) { const response = await fetch(`/api/products/${remove.dataset.delete}`, { method: 'DELETE', headers: headers() }); if (!response.ok) return alert('No se pudo ocultar el producto.'); await loadProducts(); } });
$('#form-cancel').addEventListener('click', resetForm); $('#admin-search').addEventListener('input', render); if (key) { $('#admin-key').value = key; loadProducts().catch(() => sessionStorage.removeItem('smg-admin-key')); }
